### ISSUE TITLE
一键启动失败

### ISSUE THREAD

**Issue by 263055** [Ewall1106/Doraemon#1]
第一次运行到最后，报错：

```xml
Successfully installed coloredlogs-15.0.1 contourpy-1.2.0 cycler-0.12.1 flatbuffers-23.5.26 fonttools-4.47.2 humanfriendly-10.0 imageio-2.33.1 imageio-ffmpeg-0.4.9 kiwisolver-1.4.5 lazy_loader-0.3 matplotlib-3.8.2 numexpr-2.8.8 numpy-1.26.3 onnxruntime-1.16.3 onnxruntime-gpu-1.16.3 opencv-python-4.9.0.80 packaging-23.2 pandas-2.1.4 protobuf-4.25.2 pyparsing-3.1.1 pyreadline3-3.4.1 python-dateutil-2.8.2 pytz-2023.3.post1 scikit-image-0.22.0 scipy-1.11.4 six-1.16.0 tifffile-2023.12.9 tzdata-2023.4
Collecting package metadata (current_repodata.json): failed

CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://conda.anaconda.org/nvidia/label/cuda-12.1.1/win-64/current_repodata.json>
Elapsed: -

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.
'https//conda.anaconda.org/nvidia/label/cuda-12.1.1/win-64'


Command '"E:\1aaa\AI\comfyui-portable\installer_files\conda\condabin\conda.bat" activate "E:\1aaa\AI\comfyui-portable\installer_files\env" >nul && conda install -y -c "nvidia/label/cuda-12.1.1" cuda-runtime' failed with exit status code '1'
```

第二次运行脚本后报错：
```xml

Traceback (most recent call last):
  File "E:\1aaa\AI\comfyui-portable\start.py", line 175, in <module>
    launch_webui(args.cpu)
  File "E:\1aaa\AI\comfyui-portable\start.py", line 144, in launch_webui
    os.chdir("ComfyUI")
FileNotFoundError: [WinError 2] 系统找不到指定的文件。: 'ComfyUI'
请按任意键继续. . .

```

没有开代理，并且删除文件后重新下载还是这个错误

**Comment by 263055** [comment]
初步判断依赖下载时间超时，开VPN后按操作执行命令：
conda install -y -c "nvidia/label/cuda-12.1.1" cuda-runtime'
可以顺利下载依赖，但是依然无法启动，再次下载还是提示：
```xml

Traceback (most recent call last):
  File "E:\1aaa\AI\comfyui-portable\start.py", line 175, in <module>
    launch_webui(args.cpu)
  File "E:\1aaa\AI\comfyui-portable\start.py", line 144, in launch_webui
    os.chdir("ComfyUI")
FileNotFoundError: [WinError 2] 系统找不到指定的文件。: 'ComfyUI'
请按任意键继续. . .

```
